apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: policywall-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: policywall-system/policywall-webhook-cert
webhooks:
- name: mutate.policy.casbin.org
  admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    service:
      name: policywall-webhook-service
      namespace: policywall-system
      path: /mutate
  failurePolicy: Fail
  matchPolicy: Equivalent
  namespaceSelector:
    matchExpressions:
    - key: policywall.casbin.org/enabled
      operator: In
      values: ["true"]
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups: ["*"]
    apiVersions: ["*"]
    operations: ["CREATE", "UPDATE"]
    resources: ["*"]
    scope: "*"
  sideEffects: None
  timeoutSeconds: 10
