apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: policywall-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: policywall-system/policywall-webhook-cert
webhooks:
- name: vpod.policy.casbin.org
  admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    service:
      name: policywall-webhook-service
      namespace: policywall-system
      path: /validate-v1-pod
  failurePolicy: Fail
  matchPolicy: Equivalent
  namespaceSelector:
    matchExpressions:
    - key: policywall.casbin.org/enabled
      operator: In
      values: ["true"]
  objectSelector: {}
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["pods"]
    scope: "*"
  sideEffects: None
  timeoutSeconds: 10
