apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "policywall.fullname" . }}
  labels:
    {{- include "policywall.labels" . | nindent 4 }}
rules:
  - apiGroups: ["policywall.casbin.org"]
    resources: ["admissionpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policywall.casbin.org"]
    resources: ["admissionpolicies/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "policywall.fullname" . }}
  labels:
    {{- include "policywall.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "policywall.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "policywall.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
